version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-fastapi
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    environment:
      # Redis connection details
      - REDIS_HOST=redis
      - REDIS_PORT=6379

      # Mongo connection details
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=fastapi_db
      
    # If you have secrets like OPENAI_API_KEY in a .env, you could do:
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    # No environment needed unless you want a custom config.
    # If you want persistent data, consider volumes.

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    # environment:
    #   # Use these if you want MongoDB to run with authentication
    #   # (comment out if you just want a no-auth local dev environment)
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo_data:/data/db  # (Optional) Persist data locally
